name: PR Workflow

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install dev dependencies
        run: npm ci
      - name: Build Backend
        run: 'npm run build:backend'
      - name: Test Backend
        run: npm run test
